name: Build_PS3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Toolchain
        run: |
          # Качаем инструменты для PS3 вручную
          wget https://github.com
          sudo tar xfz ps3dev-ubuntu-22.04-latest.tar.gz -C /
          echo "PS3DEV=/usr/local/ps3dev" >> $GITHUB_ENV
          echo "PSL1GHT=/usr/local/ps3dev/psl1ght" >> $GITHUB_ENV
          echo "/usr/local/ps3dev/bin" >> $GITHUB_PATH
          echo "/usr/local/ps3dev/ppu/bin" >> $GITHUB_PATH
          echo "/usr/local/ps3dev/spu/bin" >> $GITHUB_PATH

      - name: Build PKG
        run: |
          make

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: My_PS3_App
          path: ./*.pkg
